# Generated by Django 5.0.7 on 2024-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('current_team', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
    ]
