# Generated by Django 5.0.7 on 2024-07-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
